version: "3.7"

services:
  postgres:
    image: postgres:16-alpine
    container_name: superset_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - superset-network

  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
    networks:
      - superset-network

  superset:
    image: apache/superset:latest
    container_name: superset
    env_file:
      - .env
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
      SUPERSET_CONFIG_PATH: "/app/superset_config.py"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/superset_config.py
      - ./.env:/app/.env
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    command: >
      bash -c "
      python -m pip install pyathena &&
      superset fab create-admin --username ${SUPERSET_ADMIN_USER} --firstname Superset --lastname Admin --email admin@superset.com --password ${SUPERSET_ADMIN_PWD} &&
      superset db upgrade &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - superset-network

volumes:
  postgres_data:
  superset_home:
  redis:

networks:
  superset-network:
    driver: bridge
