name: Trivy Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy FS scan (high/critical only, fail on findings)
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo aquasec/trivy fs --severity HIGH,CRITICAL --exit-code 1 /repo

      - name: Run Trivy config scan (high/critical only, fail on findings)
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo aquasec/trivy config --severity HIGH,CRITICAL --exit-code 1 /repo